### ISSUE TITLE
Configuration issue with Anaconda and Python 3.8

### ISSUE THREAD

**Issue by JAM5107k** [edwardoughton/itmlogic#75]
I followed the installation directions on the README. However, my version of Anaconda only goes back to python 3.8. I did the following:
1. conda create --name itmlogic python=3.8 gdal
2. conda activate itmlogic
3. conda install numpy fiona shapely rtree rasterio pyproj tqdm pytest rasterstats pandas matplotlib
4. git clone https://github.com/edwardoughton/itmlogic
5. changed to the itmlogic directory
6. python setup.py install
7. python -m pytest

The result is below (2 fails):

--------------------------------------- Captured stdout call ---------------------------------------
Line of sight path
Diffraction is the dominant mode
Estimated quantiles of basic transmission loss (db)
Free space value 102.63079048306626 db
Confidence levels 50, 90, 10
===================================== short test summary info ======================================
FAILED tests/test_area.py::test_itmlogic_area - assert 111.69200844812512 == 111.69200844812511
FAILED tests/test_p2p.py::test_itmlogic_p2p - assert 137.64279211442658 == 137.64279211442656
=================================== 2 failed, 19 passed in 0.31s ===================================

Looking at the 2 failures it appears that there is an assert on the equivlancy of some doubles that differ in the 14th decimal place. 

Any suggestions?

Thanks /Joe.

**Comment by JAM5107k** [comment]
If I continue on and just try the p2p.py test it also fails. Here are the results:

python scripts/p2p.py 

Traceback (most recent call last):
  File "scripts/p2p.py", line 28, in <module>
    from terrain_module import terrain_p2p
  File "/Analysis/propagation/itmlogic/scripts/terrain_module.py", line 21, in <module>
    from rasterstats import gen_zonal_stats, point_query
  File "/opt/anaconda3/envs/itmlogic/lib/python3.8/site-packages/rasterstats/__init__.py", line 2, in <module>
    from .main import gen_zonal_stats, raster_stats, zonal_stats
  File "/opt/anaconda3/envs/itmlogic/lib/python3.8/site-packages/rasterstats/main.py", line 8, in <module>
    import numpy.distutils.system_info as sysinfo
  File "/opt/anaconda3/envs/itmlogic/lib/python3.8/site-packages/numpy/distutils/system_info.py", line 196, in <module>
    from numpy.distutils.command.config import config as cmd_config
  File "/opt/anaconda3/envs/itmlogic/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/opt/anaconda3/envs/itmlogic/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'

Any suggestions? Thanks /Joe.

**Comment by JAM5107k** [comment]
To get past the first issue (the comparison of the float to 14 decimal places) I updated test_area.py and test_p2p.py with:

for result in output:
        if result['distance_km'] == 10 and result['confidence_level_%'] == 50:
            assert math.isclose(result['propagation_loss_dB'], 111.69200844812511, abs_tol = 1e-12)
        if result['distance_km'] == 10 and result['confidence_level_%'] == 90:
            assert math.isclose(result['propagation_loss_dB'], 121.59437954264777, abs_tol = 1e-12)
        if result['distance_km'] == 10 and result['confidence_level_%'] == 10:
            assert math.isclose(result['propagation_loss_dB'], 101.78963735360244, abs_tol = 1e-12)
        if result['distance_km'] == 500 and result['confidence_level_%'] == 50:
            assert math.isclose(result['propagation_loss_dB'], 215.27421197676375, abs_tol = 1e-12)
        if result['distance_km'] == 500 and result['confidence_level_%'] == 90:
            assert math.isclose(result['propagation_loss_dB'], 221.71014370503855, abs_tol = 1e-12)
        if result['distance_km'] == 500 and result['confidence_level_%'] == 10:
            assert math.isclose(result['propagation_loss_dB'], 208.83828024848896, abs_tol = 1e-12)

With this we are only testing 12 decimal places and the 14 decimal place discrepancy is resolved. This is an examplefrom test_area.py but test_p2p.py is similar. 

I have migrated on to a later version of python and there are other issues related to depricated modules. Trying to work through those.
